-- Complete Quirino Province Barangays (132 total)
-- As of 2020 Census

-- Delete old sample data
DELETE FROM public.barangays;

-- Insert all Quirino barangays
INSERT INTO public.barangays (name, municipality, island_group, is_active) VALUES
-- Aglipay (25 barangays)
('Alicia', 'Aglipay', 'Luzon', true),
('Cabugao', 'Aglipay', 'Luzon', true),
('Dagupan', 'Aglipay', 'Luzon', true),
('Diodol', 'Aglipay', 'Luzon', true),
('Dumabel', 'Aglipay', 'Luzon', true),
('Dungo', 'Aglipay', 'Luzon', true),
('Guinalbin', 'Aglipay', 'Luzon', true),
('Ligaya', 'Aglipay', 'Luzon', true),
('Nagabgaban', 'Aglipay', 'Luzon', true),
('Palacian', 'Aglipay', 'Luzon', true),
('Pinaripad Norte', 'Aglipay', 'Luzon', true),
('Pinaripad Sur', 'Aglipay', 'Luzon', true),
('Progreso', 'Aglipay', 'Luzon', true),
('Ramos', 'Aglipay', 'Luzon', true),
('Rang-ayan', 'Aglipay', 'Luzon', true),
('San Antonio', 'Aglipay', 'Luzon', true),
('San Benigno', 'Aglipay', 'Luzon', true),
('San Francisco', 'Aglipay', 'Luzon', true),
('San Leonardo', 'Aglipay', 'Luzon', true),
('San Manuel', 'Aglipay', 'Luzon', true),
('San Ramon', 'Aglipay', 'Luzon', true),
('Victoria', 'Aglipay', 'Luzon', true),
('Villa Pagaduan', 'Aglipay', 'Luzon', true),
('Villa Santiago', 'Aglipay', 'Luzon', true),
('Villa Ventura', 'Aglipay', 'Luzon', true),

-- Cabarroguis (17 barangays)
('Banuar', 'Cabarroguis', 'Luzon', true),
('Burgos', 'Cabarroguis', 'Luzon', true),
('Calaocan', 'Cabarroguis', 'Luzon', true),
('Del Pilar', 'Cabarroguis', 'Luzon', true),
('Dibibi', 'Cabarroguis', 'Luzon', true),
('Dingasan', 'Cabarroguis', 'Luzon', true),
('Eden', 'Cabarroguis', 'Luzon', true),
('Gomez', 'Cabarroguis', 'Luzon', true),
('Gundaway', 'Cabarroguis', 'Luzon', true),
('Mangandingay', 'Cabarroguis', 'Luzon', true),
('San Marcos', 'Cabarroguis', 'Luzon', true),
('Santo Domingo', 'Cabarroguis', 'Luzon', true),
('Tucod', 'Cabarroguis', 'Luzon', true),
('Villa Peña', 'Cabarroguis', 'Luzon', true),
('Villamor', 'Cabarroguis', 'Luzon', true),
('Villarose', 'Cabarroguis', 'Luzon', true),
('Zamora', 'Cabarroguis', 'Luzon', true),

-- Diffun (34 barangays)
('Aklan Village', 'Diffun', 'Luzon', true),
('Andres Bonifacio', 'Diffun', 'Luzon', true),
('Aurora East', 'Diffun', 'Luzon', true),
('Aurora West', 'Diffun', 'Luzon', true),
('Baguio Village', 'Diffun', 'Luzon', true),
('Balagbag', 'Diffun', 'Luzon', true),
('Bannawag', 'Diffun', 'Luzon', true),
('Cajel', 'Diffun', 'Luzon', true),
('Campamento', 'Diffun', 'Luzon', true),
('Diego Silang', 'Diffun', 'Luzon', true),
('Don Faustino Pagaduan', 'Diffun', 'Luzon', true),
('Don Mariano Perez, Sr.', 'Diffun', 'Luzon', true),
('Doña Imelda', 'Diffun', 'Luzon', true),
('Dumanisi', 'Diffun', 'Luzon', true),
('Gabriela Silang', 'Diffun', 'Luzon', true),
('Gregorio Pimentel', 'Diffun', 'Luzon', true),
('Gulac', 'Diffun', 'Luzon', true),
('Guribang', 'Diffun', 'Luzon', true),
('Ifugao Village', 'Diffun', 'Luzon', true),
('Isidro Paredes', 'Diffun', 'Luzon', true),
('Liwayway', 'Diffun', 'Luzon', true),
('Luttuad', 'Diffun', 'Luzon', true),
('Magsaysay', 'Diffun', 'Luzon', true),
('Makate', 'Diffun', 'Luzon', true),
('Maria Clara', 'Diffun', 'Luzon', true),
('Rafael Palma', 'Diffun', 'Luzon', true),
('Ricarte Norte', 'Diffun', 'Luzon', true),
('Ricarte Sur', 'Diffun', 'Luzon', true),
('Rizal', 'Diffun', 'Luzon', true),
('San Antonio', 'Diffun', 'Luzon', true),
('San Isidro', 'Diffun', 'Luzon', true),
('San Pascual', 'Diffun', 'Luzon', true),
('Villa Pascua', 'Diffun', 'Luzon', true),

-- Maddela (32 barangays)
('Abbag', 'Maddela', 'Luzon', true),
('Balligui', 'Maddela', 'Luzon', true),
('Buenavista', 'Maddela', 'Luzon', true),
('Cabaruan', 'Maddela', 'Luzon', true),
('Cabua-an', 'Maddela', 'Luzon', true),
('Cofcaville', 'Maddela', 'Luzon', true),
('Diduyon', 'Maddela', 'Luzon', true),
('Dipintin', 'Maddela', 'Luzon', true),
('Divisoria Norte', 'Maddela', 'Luzon', true),
('Divisoria Sur', 'Maddela', 'Luzon', true),
('Dumabato Norte', 'Maddela', 'Luzon', true),
('Dumabato Sur', 'Maddela', 'Luzon', true),
('Jose Ancheta', 'Maddela', 'Luzon', true),
('Lusod', 'Maddela', 'Luzon', true),
('Manglad', 'Maddela', 'Luzon', true),
('Pedlisan', 'Maddela', 'Luzon', true),
('Poblacion Norte', 'Maddela', 'Luzon', true),
('Poblacion Sur', 'Maddela', 'Luzon', true),
('San Bernabe', 'Maddela', 'Luzon', true),
('San Dionisio I', 'Maddela', 'Luzon', true),
('San Martin', 'Maddela', 'Luzon', true),
('San Pedro', 'Maddela', 'Luzon', true),
('San Salvador', 'Maddela', 'Luzon', true),
('Santa Maria', 'Maddela', 'Luzon', true),
('Santo Niño', 'Maddela', 'Luzon', true),
('Santo Tomas', 'Maddela', 'Luzon', true),
('Villa Agullana', 'Maddela', 'Luzon', true),
('Villa Gracia', 'Maddela', 'Luzon', true),
('Villa Hermosa Norte', 'Maddela', 'Luzon', true),
('Villa Hermosa Sur', 'Maddela', 'Luzon', true),
('Villa Jose V Ylanan', 'Maddela', 'Luzon', true),
('Ysmael', 'Maddela', 'Luzon', true),

-- Nagtipunan (16 barangays)
('Anak', 'Nagtipunan', 'Luzon', true),
('Asaklat', 'Nagtipunan', 'Luzon', true),
('Dipantan', 'Nagtipunan', 'Luzon', true),
('Dissimungal', 'Nagtipunan', 'Luzon', true),
('Guino', 'Nagtipunan', 'Luzon', true),
('La Conwap', 'Nagtipunan', 'Luzon', true),
('Landingan', 'Nagtipunan', 'Luzon', true),
('Mataddi', 'Nagtipunan', 'Luzon', true),
('Matmad', 'Nagtipunan', 'Luzon', true),
('Old Gumiad', 'Nagtipunan', 'Luzon', true),
('Ponggo', 'Nagtipunan', 'Luzon', true),
('San Dionisio II', 'Nagtipunan', 'Luzon', true),
('San Pugo', 'Nagtipunan', 'Luzon', true),
('San Ramos', 'Nagtipunan', 'Luzon', true),
('Sangbay', 'Nagtipunan', 'Luzon', true),
('Wasid', 'Nagtipunan', 'Luzon', true),

-- Saguday (9 barangays)
('Cardenas', 'Saguday', 'Luzon', true),
('Dibul', 'Saguday', 'Luzon', true),
('Gamis', 'Saguday', 'Luzon', true),
('La Paz', 'Saguday', 'Luzon', true),
('Magsaysay', 'Saguday', 'Luzon', true),
('Rizal', 'Saguday', 'Luzon', true),
('Salvacion', 'Saguday', 'Luzon', true),
('Santo Tomas', 'Saguday', 'Luzon', true),
('Tres Reyes', 'Saguday', 'Luzon', true),
('Tuao', 'Saguday', 'Luzon', true);

-- Verify insert
SELECT COUNT(*) as total_barangays, 
       COUNT(DISTINCT municipality) as municipalities
FROM public.barangays;
